// Generates src/lib/engine/README.md from the live tactic catalogue and risk config.
import { writeFileSync } from "node:fs";
import { TACTIC_INFO } from "../src/lib/data/families";
import { DEFAULT_RISK_CONFIG, BENIGN_MARKERS } from "../src/lib/engine/risk";
import { TACTICS } from "../src/lib/engine/types";

const cfg = DEFAULT_RISK_CONFIG;
const lines: string[] = [];
lines.push(`# The risk engine, in numbers`);
lines.push(``);
lines.push(`Generated by \`npm run engine:readme\` from \`src/lib/data/families.ts\` and \`src/lib/engine/risk.ts\`. Every number below is the one the code uses.`);
lines.push(``);
lines.push(`## Pipeline for one fragment`);
lines.push(``);
lines.push(`1. **Retrieve.** Moss \`queryMultiIndex\` over the playbook (+ community intel), \`alpha = 1.0\`, top-${Number(process.env.RAKSHA_TOPK ?? 6)} → raw cosine scores.`);
lines.push(`2. **Calibrate.** \`confidence = clamp((score − floor) / (ceil − floor), 0, 1)\` with floor ${process.env.RAKSHA_SCORE_FLOOR ?? 0.38}, ceil ${process.env.RAKSHA_SCORE_CEIL ?? 0.72} (moss-minilm).`);
lines.push(`3. **Gate.** Fragments under ${cfg.minWords} words are ignored. Caller fragments containing a *benign marker* (see below) are ignored. If the best benign look-alike scores within ${cfg.benignMargin} of the best tactic line, the fragment is ignored.`);
lines.push(`4. **Credit.** Tactic lines within ${cfg.creditBand} of the best tactic line (max ${cfg.creditTopN}) are credited with rank discounts 1.0 / 0.75 / 0.55; anything below confidence ${cfg.minConfidence} is dropped. The protected person's words can only credit \`victim_compliance\` lines; the caller's words never can.`);
lines.push(`5. **Accumulate.** Per tactic, keep the best \`confidence × (0.6 + 0.4 × severity/5)\` seen in the call.`);
lines.push(`6. **Score.** \`score = 100 × (1 − Π_t (1 − weight_t × ${cfg.singleTacticCap} × conf_t))\`, then rules: pressure + ask (each ≥ ${cfg.triadConfidence}) ⇒ ≥ ${cfg.levels.danger + 15}; compliance under pressure ⇒ ≥ 85; ≥ 4 distinct tactics across ≥ 2 fragments ⇒ ≥ ${cfg.levels.danger}; 3 distinct ⇒ ≥ ${cfg.levels.caution + 10}.`);
lines.push(`7. **Level.** safe < ${cfg.levels.caution} ≤ caution < ${cfg.levels.danger} ≤ danger.`);
lines.push(``);
lines.push(`## Tactic weights`);
lines.push(``);
lines.push(`| Tactic | Weight | Pressure | Ask | Alone, at full confidence |`);
lines.push(`|---|---|---|---|---|`);
for (const t of TACTICS) {
  const i = TACTIC_INFO[t];
  const alone = Math.round((1 - (1 - i.weight * cfg.singleTacticCap)) * 100);
  lines.push(`| ${i.label} (\`${t}\`) | ${i.weight} | ${i.pressure ? "✓" : ""} | ${i.ask ? "✓" : ""} | ${alone} |`);
}
lines.push(``);
lines.push(`"Alone" is the score a single tactic can reach by itself: at most 32, barely into CAUTION and far from DANGER (${cfg.levels.danger}); the score comes from *combinations*, which is what a scam script is.`);
lines.push(``);
lines.push(`## Benign markers (regular expressions)`);
lines.push(``);
for (const re of BENIGN_MARKERS) lines.push(`- \`${re.source}\``);
lines.push(``);
lines.push(`## Worked example`);
lines.push(``);
lines.push(`Authority (0.8) at confidence 0.8 → 1 − (1 − 0.8·${cfg.singleTacticCap}·0.8) = ${(1 - (1 - 0.8 * cfg.singleTacticCap * 0.8)).toFixed(3)} → score ${Math.round((1 - (1 - 0.8 * cfg.singleTacticCap * 0.8)) * 100)} (safe). Add urgency (0.8 @ 0.8): score ${Math.round((1 - (1 - 0.8 * cfg.singleTacticCap * 0.8) ** 2) * 100)} (caution). Add an OTP request (1.0 @ 0.8): triad ⇒ ${cfg.levels.danger + 15} (danger).`);
writeFileSync("src/lib/engine/README.md", lines.join("\n") + "\n");
console.log("wrote src/lib/engine/README.md");
